# name: Deploy Production

# on main branch updates

on:

    push:

        branches:

            - main

jobs:

    deploy:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

              with:

                  node-version: "16.17.1"
              

              #install serverless

            - name: Install Serverless Framework

              run: npm install -g serverless

              # authentication

            - name: Serverless AWS authentication

              run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY_DEPLOY }} --secret ${{ secrets.AWS_SECRET_DEPLOY }}

              # create ENV, use the shell `cat` command to create env.yml from secrets

           # - name: Create env file
#
            #  run: |

              #    cat > env.yml << EOF

               #   ${{ secrets.ENV }}

                #  EOF

              #install node modules

            - name: Install NPM dependencies
              working-directory: backend
              run: export NODE_OPTIONS="--max-old-space-size=8192"
                   npm install
                   
            - name: Install Serverless plug in
              working-directory: backend
              run:  serverless plugin install -n serverless-webpack

              #serverless deploy

            - name: Deploy
              working-directory: backend

              run: sls deploy 
